; =========================================================
; 1. MÔI TRƯỜNG ARDUINO SLAVE (Gắn cảm biến)
; =========================================================
[env:uno_sensors]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM8  
build_src_filter = +<uno_sensors.cpp>
lib_deps =
    claws/BH1750@^1.3.0

; =========================================================
; 2. MÔI TRƯỜNG ESP32 MASTER (Gắn bơm & cắm USB vào PC)
; =========================================================
[env:esp32_master]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
upload_port = COM9
monitor_echo = yes
monitor_filters = send_on_enter
build_src_filter = +<esp32_master.cpp>  ; <--- BẠN PHẢI THÊM DÒNG NÀY VÀO ĐÂY (Tên file chứa code ESP32)

; =========================================================
; 3. MÔI TRƯỜNG ESP32-CAM (Camera)
; =========================================================
[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 9600
monitor_rts = 0
monitor_dtr = 0
board_build.partitions = huge_app.csv
build_src_filter = +<esp_camera.cpp>
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue